# Generated by Django 4.2 on 2025-07-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_de_vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prdouto',
            new_name='Produto',
        ),
    ]
