# Generated by Django 4.2 on 2025-07-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_de_vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedores',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
