# Generated by Django 4.2 on 2025-07-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_de_vendas', '0002_remove_produto_fornecedores_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
