# Generated by Django 4.2 on 2025-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_de_vendas', '0004_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='email.padrao@exemplo.com', max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
